language: node_js
node_js:
- '0.12'
services:
- mongodb
- elasticsearch
before_script:
- sleep 15

deploy:
  provider: heroku
  api_key:
    secure: "BaeaKT5jlZoEwz2pTDVbuDHyT/FaXdLQp/IJHld3pMloxeq2X4dO++eFN/LqBhCH0CoihJb7n5VcIQb8gvqlL0GKI9C+fMGw5M4giHNn2FpBsKX3hBiQtlP39fQHtkNbjbt++BoAJcsBW7lzEO0HJ0FdNUTkASA6eR145FvtcfE="
  app:
    master: ad-landsat-api
    develop: ad-landsat-api-staging
  on:
    repo: AstroDigital/landsat-api
