language: node_js
node_js:
- '0.12'
services:
- mongodb
- elasticsearch
before_script:
- sleep 15

deploy:
  provider: heroku
  api_key:
    secure: "RFU+GmNuP5ZfBjuZOfZGQ12UOuVLd5V7jFJCRIVDSK8cfjNpvMXxr0C2x7Vada41Dq0qvtfZcgXRf7CKHCWRWjaQvb9XVMX6bmLAvyS90HEiJTXrvCFu/q4L70EUdzKn+TwqZ4MjoZ6Wwv46h4Bjz0KWc2LABjMuhEhMyuN8zW8="
  app:
    master: ad-landsat-api
    develop: ad-landsat-api-staging
  on:
    repo: AstroDigital/landsat-api
